# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "webserver"
  config.vm.network "public_network", bridge: "ens33"
  config.vm.provision "shell", inline: <<-SHELL
    # Install Ansible
    yum install -y https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.4.0.0-1.el7.ans.noarch.rpm
    echo `hostname`
  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "webserver.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "webserver"
    ansible.ask_vault_pass = true
  end
end
